language: java
sudo: false #faster builds

jdk:
  - oraclejdk8

before_script:
  - chmod +x gradlew

script:
  - ./gradlew clean test
  - ./gradlew jacocoTestReport

cache:
  directories:
    - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash)